import Head from "next/head";
import type { AppProps } from "next/app";

import "../src/styles/style.global.scss";

import StatsContextProvider from "../src/context/StatsContextProvider";
import SettingsContextProvider from "../src/context/SettingsContextProvider";
import ProgressContextProvider from "../src/context/ProgressContextProvider";

function MyApp({ Component, pageProps }: AppProps) {
    return (
        <StatsContextProvider>
            <SettingsContextProvider>
                <ProgressContextProvider>
                    <Head>
                        <title>Create Next App</title>
                        <meta
                            name="description"
                            content="Generated by create next app"
                        />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                    <Component {...pageProps} />
                </ProgressContextProvider>
            </SettingsContextProvider>
        </StatsContextProvider>
    );
}

export default MyApp;
