enum LocalStorageKeyEnum {
    // Progress Context
    PROGRESS_ANSWERED_QS = "PROGRESS_ANSWERED_QUESTIONS",
    PROGRESS_LVL_KEY = "PROGRESS_LEVEL_KEY",
    PROGRESS_GRAVEYARD_QS = "PROGRESS_GRAVEYARD_QUESTIONS",

    // Settings Context
    SETTING_AUTOPLAY = "SETTING_AUTOPLAY_IS_ON",
    SETTING_SHOW_FURI = "SETTING_SHOW_FURIGANA",
    SETTING_SHOW_ENG = "SETTING_SHOW_ENGLISH",

    // Stats Context
    STATS_ATTEMPTS_CORRECT = "STATS_TOTAL_ATTEMPTS_CORRECT",
    STATS_ATTEMPTS_ALL = "STATS_TOTAL_ATTEMPTS_ALL",
}

export default LocalStorageKeyEnum;
